<?php

namespace AppBundle\Repository;

/**
 * BattleWarriorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BattleWarriorRepository extends \Doctrine\ORM\EntityRepository
{
}
