<?php

namespace AppBundle\Repository;
use Doctrine\ORM\Query\ResultSetMapping;

/**
 * BattleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BattleRepository extends \Doctrine\ORM\EntityRepository
{
}
