<?php

namespace AppBundle\Repository;

/**
 * BuiildingTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BuiildingTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
