<?php

namespace AppBundle\Repository;

/**
 * BuildingCostsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BuildingCostsRepository extends \Doctrine\ORM\EntityRepository
{
}
