<?php

namespace AppBundle\Repository;

/**
 * StockTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StockTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
