<?php

namespace AppBundle\Repository;

/**
 * WarriorRequirementsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WarriorRequirementsRepository extends \Doctrine\ORM\EntityRepository
{
}
