<?php

namespace AppBundle\Repository;

/**
 * WarriorCostsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WarriorCostsRepository extends \Doctrine\ORM\EntityRepository
{
}
