<?php

namespace AppBundle\Repository;

/**
 * WarriorTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WarriorTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
